### ISSUE TITLE
Implement reverse scan for query

### ISSUE THREAD

**Issue by jfunston** [futurewei-cloud/chogori-platform#59]

**Comment by jfunston** [comment]
Reverse scan is a bit more complicated than forward scan for the SKV query because of the routing of multi-partition requests. When the scan reaches a partition boundary, the server needs to specify a key to use as the continuation token. The continuation token key will be used by the PartitionRequest method to route the request to the server based on the partition map. The request also need to work correctly in the situation of a partition map change (such as partition split or merge). As the code is now we do not have a good way to do this for a reverse scan because the partition map interprets partition ends as exclusive (in other words, with a key alone we don't have a way to specify the "previous partition").


To support reverse scan we need to add an "exclusive" flag to the query response continuation token. This will tell the client to consider the token exclusive. The query request will also need an "exclusiveStart" flag that tells the server whether the start key should be included in the result set. PartitionRequest will also need to be modified with a new parameter that tells it whether to consider end keys as inclusive and start keys as exclusive in the partition map (it can have a default value of false so that current uses of PartitionRequest do not need to be changed). When the client gets a response back with the exclusive flag in the continuation token set to true, then it needs to set the flag in the PartitionRequest and the exclusiveStart flag in the query request.


An empty partition and range key string should mean "end of table" for a start key of a reverse scan and an empty partition and range key should mean "start of table" for an end key of a reverse scan. The user creates these with SKVRecords where no serialize methods are called. Note that this is different than if the user calls skipNext on their SKVRecords. If the user specifies "end of table" for the start key then the exclusive flags will need to be set for the first request.

**Comment by jfunston** [comment]
Some background information on PartitionRequest for extra context. PartitionRequest wraps an RPC that is meant to be handled by a logical data partition (as opposed to a particular physical server). It uses the partition map and the key from the request to find the correct destination. If the partition map is stale, PartitionRequest automatically handles refreshing it. PartitionRequest also handles retries when the response status indicates a retriable error. We want any data-path requests to have this functionality so they should all use this interface.

**Comment by YazhiFeng** [comment]
Implement reverse scan for query:
1. 'exclusiveToken' parameter is added to the QueryResponse. It indicate whether 'nextToScan' key is included in the next round of scan. 
2. 'exclusiveKey' parameter is added to the QueryRequest. It will be set according to the QueryResponse. For now, I do not add an api to set 'exclusiveKey' be true at the first time.
3. PartitionRequest also have to modified to find an appropriate partition. Two parameters are added: 'reverse' and 'exclusiveKey', which default set to false. Accordingly, function 'getPartitionForKey' is also modified that 'reverse' and 'exclusiveKey' are also added.
4. Some other minor modifications are made. E.g. In handleQuery, change '_validateReadRequest' to '_validateQueryRequest' because the judging condition changes. 
5. Reverse scan test cases are added in the QueryTest (scenario02).
